### PR TITLE
Add search prefix back again

### PR DESCRIPTION
**Pull request by lunaryorn**

### CODE REVIEW

**Comment by lunaryorn** [comment]
Sorry, I can't follow you :blush: What do you mean?

**Comment by Jomik** [comment]
Just mean that you are pushing a ton of PRs, really nice :D
IIUC, the search prefix is removed if it doesn't manage to find any matches ?

**Comment by lunaryorn** [comment]
@Jomik Thanks :blush:

My intention is to remove the search prefix from the `terms` before matching terms against the project info.  Otherwise we'd try to find the prefix in the project path or project name and that's probably not a good idea.

Did I make a mistake?

**Comment by Jomik** [comment]
OH, no you did not. I read through one thing, and my brain decided that it did something completely different, while I was writing the comment.
My bad - was multitasking at work 😂

**Comment by lunaryorn** [comment]
Thanks :)

**Pull request merged**
