### PR TITLE
Add content to README

### PR DESCRIPTION
**Pull request by lunaryorn**
I added a bit of content to the README, most notably some installation instructions.

I'd also like to set the URL of this Github repo to the Gnome Extensions URL to link the two, but I lack the rights to do so.

### CODE REVIEW

**Comment by lunaryorn** [comment]
@Jomik Can you set <https://extensions.gnome.org/extension/1207/vscode-search-provider/> as website of this Github repo?  I just realized that the Gnome Ext. page links to this repo but not the other way around.

**Comment by Jomik** [comment]
I am not sure where you'd like me to link to the GNOME extensions website. I think it is normally put in the README?

**Comment by lunaryorn** [comment]
@Jomik 
grafik

Here :slightly_smiling_face:

**Comment by Jomik** [comment]
Done, thanks! :)

**Pull request merged**
