### PR TITLE
Support new format of recently opened workspaces and files introduced…

### PR DESCRIPTION
**Pull request by elwerene**
… in https://github.com/Microsoft/vscode/issues/54933

### CODE REVIEW

**Comment by Jomik** [comment]
Looks good, thank you!

**Comment by elwerene** [comment]
@Jomik Please update the version on extensions.gnome.org. Thank you!

**Comment by Jomik** [comment]
Will try to remember to do this as soon as I get on my Linux machine.

**Comment by elwerene** [comment]
If you are not regularly on Linux, your extensions works well on 3.28.3 (Fedora 28).

**Comment by Jomik** [comment]
:+1: I've added 3.28 and 3.30, and submitted an update. Thank you!

**Pull request merged**
