### PR TITLE
Use correct executable for launch from gui

### PR DESCRIPTION
**Pull request by elwerene**
Fixes problems with missing environment variables like ${env:NVM_BIN}.

In my case it uses `/usr/share/code/code` instead of `/usr/bin/code`.

I couldn't check if this works with flatpak. It should work with all other install versions though. I think the extension could not work with flatpak anyways as `code` would not be a valid command anyways.

### CODE REVIEW

**Comment by Jomik** [comment]
Looks good, thank you! 👍

**Comment by elwerene** [comment]
Wow, you are quick! Thanks

Please don't forget to release it to extensions.gnome.org

Am 25. Januar 2019 13:44:20 MEZ schrieb Jonas Holst Damtoft <notifications@github.com>:

**Comment by Jomik** [comment]
Well, I just had to read a few lines and press a big green button! :+1:

**Comment by Jomik** [comment]
This has been released as version 11 together with #16, pending review.

**Pull request merged**
