### PR TITLE
Case insensitive search

### PR DESCRIPTION
**Pull request by SantoJambit**
This makes searches ignore case like the dashboard usually does.

Honestly, my workspaces are all lower-case, but my customers are sadly not wired that way.

### CODE REVIEW

**Comment by lunaryorn** [comment]
Please do take a look at the failing CI.

**Comment by SantoJambit** [comment]
Sorry, I thought `yarn format` does actually write it. It still needed a `--write` argument.

**Comment by swsnr** [comment]
@SantoJambit Coming back to make you aware that I'm no longer maintaining this extension, and @Jomik's deprecated it, so this extension is essentially no longer maintained, see #42   I just don't feel like going through the hassle of porting the entire thing to Gnome 40, less so given that search providers are essentially not official extension API (we're meddling with shell internals to register the provider).

This means mostly that we'll likely not to publish another release with your changes.  I'm very sorry for the wasted effort from your side; you just got caught in the Gnome 40 update with some bad timing :disappointed: 

On the upside I've taken the time to write a proper search provider for VSCode, see https://github.com/lunaryorn/gnome-search-providers-vscode 

It's not fully equivalent yet, in particular it only supports the Arch Code OSS package (but I'm open to pull requests), doesn't search files yet and has no configuration.  But it already supports Gnome 40, and properly appears in the Gnome Shell search setting, so for the first time ever you can actually configure where the VSCode results should appear in search.

**Comment by SantoJambit** [comment]
Thanks for the update @lunaryorn. I'm still on 3.38, does the new search-provider work for that as well or is it only for 40+?

**Comment by swsnr** [comment]
It works with every Gnome 3 version, even very old ones; it uses the well defined and clearly specified search provider DBus interface, and doesn't meddle with any internals of Gnome.

**Pull request merged**
