### PR TITLE
Polish settings widget

### PR DESCRIPTION
**Pull request by lunaryorn**
Improve layout with better alignment and spaces, and more structure.  Add about page with some important links and license text (see below).  Also migrate the prefs file to typescript.

settings
about

### CODE REVIEW

**Comment by lunaryorn** [comment]
@Jomik What do you think?

**Review by Jomik — APPROVED** [review]
Looks awesome 👍  I skimmed the code, nothing jumped into my eyes.

Thank you so much for maintaining this! ❤️

**Comment by lunaryorn** [comment]
@Jomik Thanks :pray:

**Comment by lunaryorn** [comment]
@Jomik I've pushed v17 with this change and #34, would you mind to upload it once Github has build the zip?

**Comment by Jomik** [comment]
> @Jomik I've pushed v17 with this change and #34, would you mind to upload it once Github has build the zip?

It has been uploaded for review 👍

**Comment by lunaryorn** [comment]
@Jomik Thanks :+1:

**Pull request merged**
