### PR TITLE
Add CI workflow

### PR DESCRIPTION
**Pull request by lunaryorn**
Compile, lint and check code formatting, but have yet to figure out how to use a docker to build the ZIP file with `gnome-extensions`.

### CODE REVIEW

**Comment by Jomik** [comment]
I don't think we need to use a docker actually. If we do, I can cook one up.
I'll see if I get time to look at this branch tomorrow :)

**Comment by lunaryorn** [comment]
> I don't think we need to use a docker actually. 

Don't know; we'll somehow get the gnome tooling onto the worker, either `gnome-extensions` for `pack` or at least the gsettings schema compiler if we bundle it with plain `zip`.  I guess docker's just the easiest way to get it, isn't it?

> I'll see if I get time to look at this branch tomorrow :)

No hurry :)  Thanks for looking at all my changes 👍

**Comment by Jomik** [comment]
Is there a reason to use a docker container and not just `zip`? I may just be way behind.
If it works, all is good I guess 👍

**Comment by lunaryorn** [comment]
Yeah that’s a good question 😇 I wanted to use gnome-extensions tool to pack the extension because that looks like the official thing, but it’s probably not worth the effort.

I’ll change it to just make a simple zip 🙂

**Comment by lunaryorn** [comment]
I've got another idea:  I'd really like to keep `gnome-extensions` as the "pack" tool, but I can add a simple Python shim to replace `gnome-extensions` on Github.  Once Github has an Ubuntu version with Gnome 3.34 or newer, we can just remove the shim :)

**Comment by Jomik** [comment]
Didn't it work with the docker container? If that is the case, then that is fine for me. The only reason to run pack on CI would be to put it in releases, so that I could easily grab a release to submit 👍

**Comment by lunaryorn** [comment]
I added a second workflow which triggers when a `v$VERSION` tag gets pushed, packages the extension and uploads the ZIP to Github releases.

**Pull request merged**
