### PR TITLE
support workspaces3 introduced in vscode 1.32

### PR DESCRIPTION
**Pull request by elwerene**
see https://github.com/Microsoft/vscode/commit/d1ba2a55fb59c94a7e1564381f97365dbed59f7a

### CODE REVIEW

**Comment by elwerene** [comment]
I don't really get why my old commits are still visible here? Souldn't they be merged already?

**Comment by Jomik** [comment]
I think the reason is that you have been working on your own master branch.
Your branch diverges from mine here, since you have merge commits.
Perhaps fork this from new, and then keep your master up to date using only fast-forward, and make PRs from a feature branch.

**Comment by elwerene** [comment]
I fixed it :)

**Comment by elwerene** [comment]
@Jomik Please merge and push a new version. Thanks :)

**Comment by Jomik** [comment]
Sent to review, though the last one just got approved the 20th of March. It's quite a slow process... :cry:

**Pull request merged**
